### ISSUE TITLE
Issues with annotation IRIs

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/rdftab.rs#5]
`gizmos.extract` created a ttl file with this line in it that won't load with ROBOT:
```
IAO:0020000 IAO:0000412 obo:iao/pno.owl .
```

Another example:
```
GO:0008150 oboInOwl:inSubset obo:go#goslim_yeast .
```

I double checked with a ttl validator and it confirmed that this syntax isn't correct:
```
$ ttl build/imports/iao.ttl 
ERROR: Unexpected "obo:iao/pno.owl" on line 139.
Validator finished with 0 warnings and 1 errors.
```

I think it should be 
```
IAO:0020000 IAO:0000412 <http://purl.obolibrary.org/obo/iao/pno.owl> .
```

... but `rdftab` reads it in and turns it into a CURIE.

Could we update handling of IRIs in annotations to be full IRIs instead of shortened to CURIEs, at least in this case? I'm not totally sure how to be smart about it and allow CURIEs when appropriate...

**Comment by jamesaoverton** [comment]
The underlying problem is that Turtle uses QNAMEs not CURIEs. IIRC: QNAMEs are limited to valid XML element names, so no slashes or hashes.

I think that I prefer for RDFTab to continue to use CURIEs everywhere, but then conversion from RDFTab to Turtle has to be a little smarter: check for invalid QNAMEs and convert them to IRIs.

**Comment by beckyjackson** [comment]
OK - no problem, I'll open an issue in Gizmos

**Comment by jamesaoverton** [comment]
It would also be nice (but harder) to make [src/turtle.sql](https://github.com/ontodev/rdftab.rs/blob/master/src/turtle.sql) smarter, eventually.
